### ISSUE TITLE
Simulating patch-like functionality

### ISSUE THREAD

**Issue by kodeninja** [imdario/mergo#107]
Given the yamls like below:

**default.yaml**:

```yaml
services:
  A:
    host: "google.com"
    path: "search"
    scheme: "https"
  B:
    host: "bing.com"
    path: "find"
logging:
  level: WARN
```

**staging.yaml**:

```yaml
services:
  A:
    path: "search2"
```

I want this merged yaml:

```yaml
services:
  A:
    host: "google.com"
    path: "search2"
    scheme: "https"
  B:
    host: "bing.com"
    path: "find"
logging:
  level: WARN
```

Is there a way to achieve this kind of behavior thru mergo? Currently, it converts `services["A"].host` and `services["A"].scheme` to `nil` in the merged object representation.

**Comment by kodeninja** [comment]
The motivation is to maintain env-specific yaml files that contain various configuration. I want to keep a base yaml (`default.yaml`) that defines all the configuration, and then for each environment (dev/staging/prod...) define only the _delta_ in those yamls to keep things DRY.

To give an equivalent from js/node, this is roughly what I'm looking for: https://runkit.com/embed/j9xi2bu00a74

And, just in case the link goes away:

```javascript
const deepmerge = require("deepmerge")
const assert = require("assert")

let defc = {
	"services": {
		"A": {
			"host": "google.com",
			"path": "search",
			"scheme": "https"
		},
		"B": {
			"host": "bing.com",
			"path": "find"
		}
	},
	"logging": {
		"level": "WARN"
	}
}

let envc = {
	"services": {
		"A": {
			"path": "search2"
		}
	}
}

let mergedc = deepmerge(defc, envc)

assert.equal("search2", mergedc.services.A.path)
assert.equal("https", mergedc.services.A.scheme)

console.log(mergedc)
```

**Comment by kodeninja** [comment]
Cross-posted on SO: https://stackoverflow.com/questions/55134454/simulating-patch-like-merging-in-go-structs-read-from-yaml-files

**Comment by mholt** [comment]
I have this question also. I'm looking into using this library, but a merge that doesn't completely replace the whole struct would be needed.

**Comment by mholt** [comment]
@kodeninja In reading your SO post, I just noticed that you use `WithOverride` transformer. I don't think it should happen if you remove that transformer. (See this project's readme examples.)

**Comment by kodeninja** [comment]
@mholt I've tried both with and without override enabled, and neither gets me the behavior I want.

**Comment by alexellis** [comment]
@mholt I have a similar issue, to this and to #130

The example is:

base:

```yaml
secrets:
 - name: a
    value: a
 - name: b
    value: b
```

override:

```yaml
secrets:
 - name: b
    value: c
```

merged:

```yaml
secrets:
 - name: a
    value: a
 - name: b
    value: c
```

actual: 😞 

```yaml
secrets:
 - name: b
    value: c
```

What did you both settle on for your use-case?
